### ISSUE TITLE
Create issue templates

### ISSUE THREAD

**Issue by sarakenney** [sarakenney/PythonProjects#2]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Task list**
- [x] create issue templates
- [ ] ensure bug label used
- [ ] link to project
- [ ] link to milestone

*Please select the Project "___" and the Milestone "Testing Phase I" before submitting.
